name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/propiq
            git pull origin master --rebase
            cd frontend
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
            cd ~/propiq/backend
            ./mvnw clean package -DskipTests
            pkill -f "backend-0.0.1" || true
            nohup java -jar target/backend-0.0.1-SNAPSHOT.jar &